2025-10-01 01:57:08 UTC
Windows-11-10.0.26100-SP0
Ren'Py 8.4.1.25072401

Early init took 74 ms
Loading error handling took 36 ms
Loading script took 281 ms
Loading save slot metadata took 43 ms
Loading persistent took 0 ms
Running init code took 81 ms
Loading analysis data took 5 ms
Analyze and compile ATL took 3 ms
Reloading save slot metadata took 24 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 93 ms
Cleaning cache took 0 ms
Making clean stores took 0 ms
Initial gc took 67 ms
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 5 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 0 ms
Analyze screens took 21 ms
Save screen analysis took 24 ms
Save pyanalysis took 0 ms
Save bytecode took 0 ms
Running _start took 2 ms
Interface start took 487 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096
Cleaning stores took 0 ms
Load screen analysis took 31 ms
Analyze screens took 0 ms
Running _start took 2 ms
Resetting cache.
Early init took 17 ms
Loading error handling took 36 ms
Loading script took 244 ms
Loading save slot metadata took 32 ms
Loading persistent took 0 ms
Running init code took 60 ms
Loading analysis data took 19 ms
Analyze and compile ATL took 4 ms
Reloading save slot metadata took 27 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 86 ms
Cleaning cache took 0 ms
Making clean stores took 1 ms
Initial gc took 109 ms
DPI scale factor: 1.250000
Creating interface object took 1 ms
Init translation took 1 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 14 ms
Save screen analysis took 22 ms
Save pyanalysis took 12 ms
Save bytecode took 4 ms
Running _start took 2 ms
Interface start took 388 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 62, in script
    f "I called it 'anthropology with sleight of hand'."
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 62, in script
    f "I called it 'anthropology with sleight of hand'."
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 13 ms
Loading error handling took 19 ms
Loading script took 220 ms
Loading save slot metadata took 29 ms
Loading persistent took 0 ms
Running init code took 50 ms
Loading analysis data took 19 ms
Analyze and compile ATL took 3 ms
Reloading save slot metadata took 23 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 79 ms
Cleaning cache took 0 ms
Making clean stores took 0 ms
Initial gc took 90 ms
DPI scale factor: 1.250000
Creating interface object took 0 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 14 ms
Save screen analysis took 23 ms
Save pyanalysis took 0 ms
Save bytecode took 5 ms
Running _start took 2 ms
Interface start took 388 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 179, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 179, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 15 ms
Loading error handling took 18 ms
Loading script took 243 ms
Loading save slot metadata took 31 ms
Loading persistent took 0 ms
Running init code took 60 ms
Loading analysis data took 22 ms
Analyze and compile ATL took 4 ms
Reloading save slot metadata took 27 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 87 ms
Cleaning cache took 0 ms
Making clean stores took 2 ms
Initial gc took 100 ms
DPI scale factor: 1.250000
Creating interface object took 1 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 14 ms
Save screen analysis took 23 ms
Save pyanalysis took 1 ms
Save bytecode took 4 ms
Running _start took 2 ms
Interface start took 394 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 179, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 179, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 16 ms
Loading error handling took 21 ms
Loading script took 260 ms
Loading save slot metadata took 33 ms
Loading persistent took 0 ms
Running init code took 64 ms
Loading analysis data took 24 ms
Analyze and compile ATL took 4 ms
Reloading save slot metadata took 31 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 102 ms
Cleaning cache took 0 ms
Making clean stores took 1 ms
Initial gc took 97 ms
DPI scale factor: 1.250000
Creating interface object took 2 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 0 ms
Analyze screens took 14 ms
Save screen analysis took 30 ms
Save pyanalysis took 16 ms
Save bytecode took 7 ms
Running _start took 1 ms
Interface start took 435 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 17 ms
Loading error handling took 28 ms
Loading script took 239 ms
Loading save slot metadata took 32 ms
Loading persistent took 0 ms
Running init code took 55 ms
Loading analysis data took 21 ms
Analyze and compile ATL took 5 ms
Reloading save slot metadata took 26 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 99 ms
Cleaning cache took 0 ms
Making clean stores took 1 ms
Initial gc took 97 ms
DPI scale factor: 1.250000
Creating interface object took 0 ms
Init translation took 1 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 19 ms
Save screen analysis took 31 ms
Save pyanalysis took 0 ms
Save bytecode took 5 ms
Running _start took 2 ms
Interface start took 444 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 18 ms
Loading error handling took 19 ms
Loading script took 238 ms
Loading save slot metadata took 35 ms
Loading persistent took 0 ms
Running init code took 59 ms
Loading analysis data took 24 ms
Analyze and compile ATL took 2 ms
Reloading save slot metadata took 28 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 87 ms
Cleaning cache took 0 ms
Making clean stores took 0 ms
Initial gc took 97 ms
DPI scale factor: 1.250000
Creating interface object took 2 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 17 ms
Save screen analysis took 24 ms
Save pyanalysis took 0 ms
Save bytecode took 3 ms
Running _start took 2 ms
Interface start took 416 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 19 ms
Loading error handling took 20 ms
Loading script took 307 ms
Loading save slot metadata took 33 ms
Loading persistent took 0 ms
Running init code took 56 ms
Loading analysis data took 22 ms
Analyze and compile ATL took 2 ms
Reloading save slot metadata took 30 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 89 ms
Cleaning cache took 1 ms
Making clean stores took 0 ms
Initial gc took 101 ms
DPI scale factor: 1.250000
Creating interface object took 1 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 15 ms
Save screen analysis took 30 ms
Save pyanalysis took 0 ms
Save bytecode took 0 ms
Running _start took 2 ms
Interface start took 402 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 15 ms
Loading error handling took 19 ms
Loading script took 246 ms
Loading save slot metadata took 40 ms
Loading persistent took 0 ms
Running init code took 53 ms
Loading analysis data took 22 ms
Analyze and compile ATL took 3 ms
Reloading save slot metadata took 29 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 168 ms
Cleaning cache took 1 ms
Making clean stores took 0 ms
Initial gc took 92 ms
DPI scale factor: 1.250000
Creating interface object took 0 ms
Init translation took 0 ms
Cleaning stores took 2 ms
Load screen analysis took 0 ms
Analyze screens took 17 ms
Save screen analysis took 28 ms
Save pyanalysis took 1 ms
Save bytecode took 6 ms
Running _start took 2 ms
Interface start took 419 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096

Full traceback:
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'f' is not defined.

While running game code:
NameError: name 'f' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/script.rpy", line 180, in script
    f "A waiting napkin?"
Exception: Sayer 'f' is not defined.
Resetting cache.
Early init took 14 ms
Loading error handling took 19 ms
Loading script took 242 ms
Loading save slot metadata took 31 ms
Loading persistent took 0 ms
Running init code took 53 ms
Loading analysis data took 26 ms
Analyze and compile ATL took 3 ms
Reloading save slot metadata took 27 ms
Backing up script files to 'C:\\Users\\Julia Do\\AppData\\Roaming/RenPy/backups\\once-upon-aao':
Dump and make backups took 88 ms
Cleaning cache took 0 ms
Making clean stores took 2 ms
Initial gc took 123 ms
DPI scale factor: 1.250000
Creating interface object took 2 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 25 ms
Save screen analysis took 37 ms
Save pyanalysis took 0 ms
Save bytecode took 8 ms
Running _start took 2 ms
Interface start took 492 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1200)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 24.10.20.26.250814'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1200, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1804, 1015) drawable=(1804, 1015)
Maximum texture size: 4096x4096
